version: '3.8'

services:
  app:
    build: .
    depends_on:
      - postgres
      - redis
      - minio
      - rabbitmq
    environment:
      - SERVER_ADDRESS=:8080
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_ADDR=redis:6379
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml:ro

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mikrotik_backup
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
    volumes:
      - miniodata:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata:
  miniodata: 